```{r setup2, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,  message=FALSE,warning=FALSE,cache=FALSE,include=FALSE, eval=TRUE)
suppressMessages({
  library(tidyr)
  library(dplyr)
  library(DT)
  library(openxlsx)
  library(ggplot2)
  library(jsonlite)
  })

```

# Read the score data (merged and also unmerged)
```{r}
# Function to convert Python dictionary string to nested named list
convert_to_named_list <- function(python_dict_str) {
  # Replace single quotes with double quotes
  json_str <- gsub("'", "\"", python_dict_str)
  # Convert to nested named list
  fromJSON(json_str)
}

# Function to remove the first layer ("nam") of the nested list
remove_first_layer <- function(named_list) {
  # Extract the list inside "nam"
  return(named_list$nam)
}

sum_values <- function(named_list) {
  return(sum(unlist(named_list)))
}

disease_areas <- c('atmps', 'autoimmun','breastcanc',
                   'cardiovasc','gastrointestin',
                   'immonco','infectdis',
                   'metadisord','neurodeg','respdis' )

alldat <- read.xlsx(paste0("predictions/merged_and_scored.xlsx")) %>% 
  rename(avg_score = mean) %>% 
  mutate(issue = as.character(issue))


## Unmerged data (i.e. score per embedding classifier combination)
df_overview <- read.xlsx(paste0("predictions/scored_overview.xlsx")) %>% 
  # select(pmid,prediction,method, embedding,score,title, abstract) %>%
  mutate(issue = as.character(issue))

pmid_metadata <- read.table("predictions/pmid_mapping.txt", sep = "\t")
colnames(pmid_metadata) <- c("disease_area", "query_type", "pmid")

df_overview <- df_overview %>%
  left_join(pmid_metadata, by = c("pmid"))

if ("tagging_scores" %in% colnames(df_overview)) {
  df_overview <- df_overview %>%
    mutate(tagging_scores = lapply(tagging_scores, convert_to_named_list)) %>%
    mutate(tagging_scores = lapply(tagging_scores, remove_first_layer)) %>%
    mutate(tagged_sum = sapply(tagging_scores, sum_values)) %>%
    select(-c(tagging_scores))
}

write.xlsx(df_overview, file = "all_results.xlsx")
df_overview
```

```{r}
all_results = read.xlsx(xlsxFile = "all_results.xlsx")
all_results %>% head()
```

# Keep predictions in [8 to 12 models positive result]
```{r}
if ("tagged_sum" %in% colnames(all_results)) {
  pmid_tags <- all_results %>%
    select(pmid, tagged_sum) %>%
    distinct()
}

# Move bow_pos and bow_neg embedding scores to separate dataframe for later join
pow_bow_results <- all_results %>%
  filter(embedding == "bow_pos") %>%
  group_by(pmid, disease_area, query_type) %>%
  summarise(bow_positive = sum(prediction), bow_pos_avg_score = mean(score), .groups = "keep") %>%
  ungroup()

neg_bow_results <- all_results %>%
  filter(embedding == "bow_neg") %>%
  group_by(pmid, disease_area, query_type) %>%
  summarise(neg_positive = sum(prediction), bow_neg_avg_score = mean(score), .groups = "keep") %>%
  ungroup()

all_results_filtered <- all_results %>% 
  filter(embedding != "bow_pos" & embedding != "bow_neg") %>%
  group_by(pmid, disease_area, query_type) %>% 
  summarise(models_positive = sum(prediction), avg_score = mean(score), .groups = "keep") %>% 
  ungroup()

# Combine the information from the bow_pos and bow_neg embeddings back into the main dataframe
final_results <- all_results_filtered %>%
  left_join(pow_bow_results, by = c("pmid", "disease_area", "query_type")) %>%
  left_join(neg_bow_results, by = c("pmid", "disease_area", "query_type"))

if ("tagged_sum" %in% colnames(all_results)) {
  all_results_filtered <- all_results_filtered %>%
    left_join(pmid_tags, by = c("pmid"))
}
final_results %>% head()
```

# Keep the top 100 pmids (12 positive and highest tagged_sum) per disease area
```{r}
GROUP_SIZE <- 150

# First only keep where 12 positive
final_results_filtered <- final_results %>%
  filter(models_positive == 12)

# Check if every group has at least 150 pmids
missing_groups <- final_results_filtered %>% 
  group_by(disease_area, query_type) %>%
  summarise(count = n(), .groups = "keep") %>%
  filter(count < GROUP_SIZE)

# Create ranked and sliced results
if ("tagged_sum" %in% colnames(final_results_filtered)) {
  results_ranked <- final_results %>% 
    group_by(disease_area, query_type) %>%
    arrange(desc(models_positive), desc(tagged_sum)) %>%
    slice(1:GROUP_SIZE) %>%
    ungroup()
} else {
  results_ranked <- final_results_filtered %>% 
    group_by(disease_area, query_type) %>%
    arrange(desc(bow_pos_avg_score)) %>%
    slice(1:GROUP_SIZE) %>%
    ungroup()
}

# Correct if any group has too few pmids
for (i in 1:nrow(missing_groups)) {
  missing_pmids <- GROUP_SIZE - missing_groups$count[i]
  add_pmids <- final_results %>%
    filter(models_positive == 11) %>%
    group_by(disease_area, query_type) %>%
    filter(disease_area == missing_groups$disease_area[i] & query_type == missing_groups$query_type[i]) %>%
    arrange(desc(bow_pos_avg_score)) %>%
    # Slice the top 150 - count pmids
    slice(1:missing_pmids) %>%
    ungroup()

  results_ranked <- rbind(
    results_ranked, 
    add_pmids
  )
}

# Use results_ranked to filter all_results_filtered
filtered_data <- results_ranked %>% 
  inner_join(results_ranked %>% select(pmid, disease_area, query_type), by = c("pmid", "disease_area", "query_type"))

if ("tagged_sum" %in% colnames(results_ranked)) {
  metadata <- all_results %>% select(-c(tagged_sum, prediction, method, embedding, score))
} else {
  metadata <- all_results %>% select(-c(prediction, method, embedding, score))
}

# Enrich the filtered data with the metadata from all_results
enriched_data <- left_join(filtered_data, metadata, by = c("pmid", "disease_area", "query_type")) %>% distinct()
enriched_data_sorted <- enriched_data %>%
  arrange(desc(bow_pos_avg_score)) %>%
  select(-c(neg_positive, bow_neg_avg_score))

# Rename columns for better readability
validation_results <- enriched_data_sorted %>%
  rename(
    "PMID" = pmid,
    "Disease Area" = disease_area,
    "Query Type" = query_type,
    "Positive Models" = models_positive,
    "Average Score" = avg_score,
    "Positive BOWs" = bow_positive,
    "BOW Average Score" = bow_pos_avg_score
  )
```

```{r}
write.xlsx(enriched_data, "validation_overview.xlsx")
```

```{r}
data <- read.xlsx("validation_overview.xlsx")
data
```

